baseURL = 'https://stephanzwicknagl.github.io/'
languageCode = 'en-us'
title = 'stephan zwicknagl'
theme = 'bowie'
googleAnalytics = 'M13YWWB9ZQ'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
mode="dark" # color-mode → light,dark,toggle or auto
useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
mainSections="projects"
mainSectionsTitle="my projects and contributions"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/stephanzwicknagl"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/stephan-zwicknagl/"

[[menu.main]]
name = "~/"
url = "/"
weight = 1

[[menu.main]]
name = "~/projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "~/resume"
url = "/resume"
weight = 3

# [[menu.main]]
# name = "~/about"
# url = "/about"
# weight = 4
